name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Inputting "apple, banana, apple , mango , banana" test
      id: inputting-apple-banana-apple-mango-banana-test
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: Inputting "apple, banana, apple , mango , banana" test
        setup-command: ''
        command: python3 remove_duplicates/main.py
        input: apple, banana, apple , mango , banana
        expected-output: "^apple\\nbanana\\nmango\\n?$"
        comparison-method: regex
        timeout: 10
        max-score: 2
    - name: Inputting "one,two,three" test
      id: inputting-one-two-three-test
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: Inputting "one,two,three" test
        setup-command: ''
        command: python3 remove_duplicates/main.py
        input: one,two,three
        expected-output: "^one\\ntwo\\nthree\\n?$"
        comparison-method: regex
        timeout: 10
        max-score: 2
    - name: Inputting "x,x,x,x" test
      id: inputting-x-x-x-x-test
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: Inputting "x,x,x,x" test
        setup-command: ''
        command: python3 remove_duplicates/main.py
        input: x,x,x,x
        expected-output: "^x\\n?$"
        comparison-method: regex
        timeout: 10
        max-score: 2
    - name: inputting "apple,banana,apple,mango,banana" test
      id: inputting-apple-banana-apple-mango-banana-test
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: inputting "apple,banana,apple,mango,banana" test
        setup-command: ''
        command: python3 remove_duplicates/main.py
        input: apple,banana,apple,mango,banana
        expected-output: "^apple\\nbanana\\nmango\\n?$"
        comparison-method: regex
        timeout: 10
        max-score: 1
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        INPUTTING-APPLE-BANANA-APPLE-MANGO-BANANA-TEST_RESULTS: "${{steps.inputting-apple-banana-apple-mango-banana-test.outputs.result}}"
        INPUTTING-ONE-TWO-THREE-TEST_RESULTS: "${{steps.inputting-one-two-three-test.outputs.result}}"
        INPUTTING-X-X-X-X-TEST_RESULTS: "${{steps.inputting-x-x-x-x-test.outputs.result}}"
      with:
        runners: inputting-apple-banana-apple-mango-banana-test,inputting-one-two-three-test,inputting-x-x-x-x-test,inputting-apple-banana-apple-mango-banana-test
